# Generated by Django 5.0.4 on 2024-04-26 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_app', '0008_alter_event_coordinates'),
        ('profile_app', '0009_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('num_volunteers_needed', models.IntegerField()),
                ('assigned_volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.userprofile')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event_app.event')),
            ],
        ),
    ]
