# Generated by Django 5.0.4 on 2024-04-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_alter_userprofile_image'),
        ('volunteer_roles_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrole',
            name='assigned_volunteer',
        ),
        migrations.AddField(
            model_name='volunteerrole',
            name='assigned_volunteer',
            field=models.ManyToManyField(null=True, to='profile_app.userprofile'),
        ),
    ]
