# Generated by Django 5.0.4 on 2024-04-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_alter_userprofile_image'),
        ('volunteer_roles_app', '0003_rename_assigned_volunteer_volunteerrole_assigned_volunteers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerrole',
            name='assigned_volunteers',
            field=models.ManyToManyField(blank=True, related_name='volunteer_roles', to='profile_app.userprofile'),
        ),
    ]
