# Generated by Django 5.0.4 on 2024-04-30 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_alter_event_coordinates'),
        ('volunteer_roles_app', '0004_alter_volunteerrole_assigned_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerrole',
            name='assigned_volunteers',
        ),
        migrations.AlterField(
            model_name='volunteerrole',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_roles', to='event_app.event'),
        ),
    ]
