# Generated by Django 5.0.4 on 2024-04-16 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=40, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('location', models.TextField(null=True)),
                ('interests', models.ManyToManyField(related_name='user_profiles', to='interest_app.interestcategory')),
            ],
        ),
    ]
