# Generated by Django 5.0.4 on 2024-04-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=40, null=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('location', models.TextField(null=True)),
            ],
        ),
    ]
