# Generated by Django 5.0.4 on 2024-04-15 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0001_initial'),
        ('profile_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(related_name='user_profiles', to='interest_app.interestcategory'),
        ),
    ]
