# Generated by Django 5.0.4 on 2024-04-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='users/default-profile-icon.jpg', null=True, upload_to='images/'),
        ),
    ]
