# Generated by Django 5.0.4 on 2024-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0009_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
