# Generated by Django 5.0.4 on 2024-05-02 02:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_alter_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
