# Generated by Django 5.0.4 on 2024-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0001_initial'),
        ('profile_app', '0012_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='interest_app.interestcategory'),
        ),
    ]
