# Generated by Django 5.0.4 on 2024-05-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0013_alter_userprofile_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
