# Generated by Django 5.0.4 on 2024-04-16 02:30

import django.db.models.deletion
import event_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interest_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('event_type', models.CharField(validators=[event_app.validators.validate_event_type])),
                ('virtual_event_link', models.URLField(blank=True, null=True, unique=True)),
                ('event_venue', models.CharField(blank=True, null=True)),
                ('event_venue_address', models.CharField(blank=True, null=True)),
                ('time', models.CharField()),
                ('time_zone', models.CharField()),
                ('description', models.TextField()),
                ('event_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='interest_app.interestcategory')),
            ],
        ),
    ]
