# Generated by Django 5.0.4 on 2024-04-15 00:54

import event_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('event_type', models.CharField(validators=[event_app.validators.validate_event_type])),
                ('virtual_event_link', models.URLField(null=True, unique=True, validators=[event_app.validators.validate_virtual_event])),
                ('event_venue', models.CharField(null=True, validators=[event_app.validators.validate_event_location])),
                ('event_venue_address', models.CharField(null=True, validators=[event_app.validators.validate_event_location])),
                ('time', models.CharField()),
                ('time_zome', models.CharField()),
                ('description', models.TextField()),
                ('event_photo', models.ImageField(upload_to='')),
                ('category', models.CharField()),
            ],
        ),
    ]
