# Generated by Django 5.0.4 on 2024-04-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0004_remove_event_date_remove_event_time_event_event_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
