# Generated by Django 5.0.4 on 2024-04-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0005_alter_event_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.TextField(blank=True, max_length=10000000, null=True),
        ),
    ]
