# Generated by Django 5.0.4 on 2024-04-25 15:51

import django.contrib.postgres.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0006_alter_event_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=15, default=Decimal('0.00'), max_digits=40), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
