<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-26 19:33
=======
# Generated by Django 5.0.4 on 2024-04-27 01:05
>>>>>>> 8171fe1c2fdc7437a6aada16e896e9901a747d5c

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0007_event_coordinates_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
