# Generated by Django 5.0.4 on 2024-04-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_alter_event_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_needed',
            field=models.BooleanField(default=False),
        ),
    ]
