# Generated by Django 5.0.4 on 2024-04-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0010_alter_event_coordinates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='collaborators',
            new_name='hosts',
        ),
    ]
