# Generated by Django 5.0.4 on 2024-05-01 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0011_rename_collaborators_event_hosts'),
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='to_do_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tasks', to='todo_app.todolist'),
        ),
    ]
