# Generated by Django 5.0.4 on 2024-05-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0012_event_to_do_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='to_do_list',
        ),
    ]
