# Generated by Django 5.0.4 on 2024-04-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('state_id', models.ImageField(upload_to='')),
                ('state_code', models.CharField(max_length=255)),
                ('country_id', models.IntegerField()),
                ('country_code', models.CharField(max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('flag', models.BooleanField()),
                ('wikidataid', models.CharField(max_length=255)),
            ],
        ),
    ]
