# Generated by Django 5.0.4 on 2024-04-27 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0001_initial'),
        ('states_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='flag',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='state_id',
        ),
        migrations.RemoveField(
            model_name='cities',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='states_app.states'),
            preserve_default=False,
        ),
    ]
