# Generated by Django 5.0.4 on 2024-04-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities_app', '0002_remove_cities_created_at_remove_cities_flag_and_more'),
        ('states_app', '0005_remove_states_country_id_states_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='state_id',
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='states_app.states'),
            preserve_default=False,
        ),
    ]
