# Generated by Django 5.0.4 on 2024-04-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countries',
            old_name='acronym',
            new_name='country_code',
        ),
    ]
