# Generated by Django 5.0.4 on 2024-04-29 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0002_like_dislike_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_orgin',
        ),
    ]
