# Generated by Django 5.0.4 on 2024-04-29 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0008_alter_event_coordinates'),
        ('post_app', '0003_remove_post_post_orgin'),
        ('profile_app', '0009_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='event_app.event'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_orgin',
            field=models.CharField(default='ChangeMate', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.userprofile'),
        ),
    ]
