# Generated by Django 5.0.4 on 2024-05-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_post_dislikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='context',
            field=models.TextField(max_length=1000),
        ),
    ]
