# Generated by Django 5.0.4 on 2024-05-02 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_alter_post_event'),
        ('profile_app', '0010_alter_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='profile_app.userprofile'),
            preserve_default=False,
        ),
    ]
