# Generated by Django 5.0.4 on 2024-04-30 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0010_alter_userprofile_location'),
        ('volunteer_roles_app', '0004_alter_volunteerrole_assigned_volunteers'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('preferred_contact_method', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=500)),
                ('return_volunteer', models.BooleanField(default=False)),
                ('volunteer_interest', models.TextField()),
                ('volunteer_experience', models.TextField()),
                ('application_status', models.BooleanField(default=None, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('decision_date', models.DateTimeField(blank=True, null=True)),
                ('decision_text', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_events', to='profile_app.userprofile')),
                ('decision_made_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_app.userprofile')),
                ('volunteer_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicantions', to='volunteer_roles_app.volunteerrole')),
            ],
        ),
    ]
