# Generated by Django 5.0.4 on 2024-04-30 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_application_app', '0001_initial'),
        ('volunteer_roles_app', '0005_remove_volunteerrole_assigned_volunteers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='volunteer_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='volunteer_roles_app.volunteerrole'),
        ),
    ]
