# Generated by Django 5.0.4 on 2024-05-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_application_app', '0002_alter_volunteerapplication_volunteer_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='application_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
