# Generated by Django 5.0.4 on 2024-05-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_application_app', '0003_alter_volunteerapplication_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerapplication',
            name='preferred_contact_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
