# Generated by Django 5.0.4 on 2024-04-14 00:01

import django.db.models.deletion
import interest_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_app', '0003_userprofile_display_name_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40, unique=True, validators=[interest_app.validators.validate_category])),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='profile_app.userprofile')),
            ],
        ),
    ]
