# Generated by Django 5.0.4 on 2024-04-14 00:05

import interest_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='category',
            field=models.CharField(max_length=50, unique=True, validators=[interest_app.validators.validate_category]),
        ),
    ]
