# Generated by Django 5.0.4 on 2024-04-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='user_profile',
        ),
    ]
