# Generated by Django 5.0.4 on 2024-04-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
