# Generated by Django 5.0.4 on 2024-04-27 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0001_initial'),
        ('states_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='country_id',
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='countries_app.countries'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='states',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='states',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
