# Generated by Django 5.0.4 on 2024-04-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states_app', '0002_alter_states_latitude_alter_states_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
