# Generated by Django 5.0.4 on 2024-04-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('states_app', '0003_alter_states_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='states',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
