# Generated by Django 5.0.4 on 2024-04-27 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0002_rename_acronym_countries_country_code'),
        ('states_app', '0004_alter_states_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='states',
            name='country_id',
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.ForeignKey(default='NA', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='countries_app.countries'),
            preserve_default=False,
        ),
    ]
