# Generated by Django 5.0.4 on 2024-04-14 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='display_name',
        ),
    ]
